### ISSUE TITLE
Please use newer SQLAlchemy and pg8000 versions

### ISSUE THREAD

**Issue by Cito** [zatosource/zato-build#21]
I could not get PostgreSQL connections working with Zato 2.0.2 and the current trunk.

The problem turned out to be caused by the old **pg8000 version** 1.9.10 which is used in Zato 2.0.2. After replacing it with the latest version, PostgreSQL connections worked properly. What makes matters worse is that pg8000 1.9.10 outputs misleading error messages (bug in its error reporting code), so it was hard for me to even spot the problem. This has been fixed in pg8000 1.9.11. I recommend changing the pinned version of pg8000 in versions.cfg from 1.9.10 to the current 1.10.2.

Also, the **SQLAlchemy version** should be changed from 0.9.4 to the current 0.9.9 to make the current pg8000 work properly with SQLAlchemy and benefit from bugfixes in SQLAlchemy. See the [changelog](http://docs.sqlalchemy.org/en/latest/changelog/changelog_09.html) in SQLAlchemy, note that there have been several fixes in SQLAlchemy's [pg8000 support](https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/pg8000.py).

The combination pg8000 1.10.2 + SQLAlchemy 0.9.9 works nicely for me.

**Comment by Cito** [comment]
Actually, this was meant as an issue for the zato repository, not the zato-build repository.

**Comment by dsuch** [comment]
Moved to https://github.com/zatosource/zato/issues/406

**Comment by aek** [comment]
I also experiments some issues with pg8000 error handling and also open a ticket in their project because of the need about more info about the error that happens, specifically for copy statements, I need to have the line of the copy input that have errors, in the zato actual pg8000 version I'm hacking into pg8000 error handling for give the info that I need
