### ISSUE TITLE
Install script does not install the libzmq package

### ISSUE THREAD

**Issue by Cito** [zatosource/zato-build#22]
When trying to install Zato from source on Ubuntu, I got errors during the installation of pyzmq, caused by missing zmq library and header files.

I think the problem is that libzmq3 and libzmq3-dev are missing in the `apt-get install` command in `_install-deb.sh`.

**Comment by dsuch** [comment]
Hi @Cito,

we install Zato from source a couple of times a day, from various branches, and it's the first time I hear of it.

Can you please post the output from install.sh?

Thanks.

CC @rafal-k

**Comment by dsuch** [comment]
Also, @Cito - what Zato branch and OS is it?

Thanks again :-)

**Comment by Cito** [comment]
Hi @dsuch,

I guess you're using a different base box which has these things already installed.

I'm was using a base box with Ubuntu 14.04.2 TLS Server, basic installation without any GUI or additional packages except openssh. 

These are the errors I get when running install.sh:

    Getting distribution for 'pyzmq==2.2.0.1'.
    no previously-included directories found matching 'docs/build'
    no previously-included directories found matching 'docs/gh-pages'
    warning: no previously-included files ... etc.
    ************************************************
    Configure: Autodetecting ZMQ settings...
        Custom ZMQ dir:       None
    detect/vers.c:4:17: fatal error: zmq.h: Datei oder Verzeichnis nicht gefunden
     #include "zmq.h"
                     ^
    compilation terminated.

    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    Failed with default libzmq, trying again with /usr/local

    ************************************************
    Configure: Autodetecting ZMQ settings...
        Custom ZMQ dir:       /usr/local
    detect/vers.c:4:17: fatal error: zmq.h: Datei oder Verzeichnis nicht gefunden
     #include "zmq.h"
                     ^
    compilation terminated.

    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ************************************************
    Failed to build or run libzmq detection test.

    If you expected pyzmq to link against an installed libzmq, please check to make sure:

        * You have a C compiler installed
        * A development version of Python is installed (including headers)
        * A development version of ZMQ >= 2.1.4 is installed (including headers)
        * If ZMQ is not in a default location, supply the argument --zmq=<path>
        * If you did recently install ZMQ to a default location,
          try rebuilding the ld cache with `sudo ldconfig`
          or specify zmq's location with `--zmq=/usr/local`

    If you expected to get a binary install (egg), we have those for
    current Pythons on OSX and Windows. These can be installed with
    easy_install, but PIP DOES NOT SUPPORT EGGS.

    You can skip all this detection/waiting nonsense if you know
    you want pyzmq to bundle libzmq as an extension by passing:

        `--zmq=bundled`

    I will now try to build libzmq as a Python extension
    unless you interrupt me (^C) in the next 10 seconds...
    
    Using bundled libzmq
    already have bundled/uuid
    already have bundled/zeromq
    attempting ./configure to generate platform.hpp
    Warning: failed to configure libzmq:
    /bin/sh: 1: ./configure: not found

    staging platform.hpp from: /tmp/easy_install-ZBfGO6/pyzmq-2.2.0.1/buildutils/include_linux
    ************************************************
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    ... etc.
    zip_safe flag not set; analyzing archive contents...
    zmq.__init__: module references __file__
    Got pyzmq 2.2.0.1.
    Getting distribution for 'pyzmq-static==2.2'.
    warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

    zip_safe flag not set; analyzing archive contents...
    Got pyzmq-static 2.2.

After installing libzmq3 and libzmq3-dev, the installer can install pyzmq without problems.

**Comment by Cito** [comment]
Actually, this was meant as an issue for the zato repository, not the zato-build repository.

**Comment by dsuch** [comment]
I happen to know that @rafal-k built an Ubuntu installer for 2.0.3 today using these Vagrant templates:

* https://github.com/zatosource/zato-build/blob/master/ansible/vagrant/build/vm/ubuntu-14.04-64/Vagrantfile.template

* https://github.com/zatosource/zato-build/blob/master/ansible/vagrant/build/vm/ubuntu-14.04-32/Vagrantfile.template

What was the image you were using?

**Comment by Cito** [comment]
I was using my own base box for Ubuntu 14.04 64bit, but got the same issue when using that Vagrantfile with the Ubuntu 14.04 64bit base box specified there taken from the cloud.

Note that the installation does not stop with that error, it just appears in the output of the install.sh script.

**Comment by dsuch** [comment]
Ah, OK, I get it now - in that case this is harmless, it's an information - Zato connections to ZeroMQ as such will work just fine. I didn't catch initially what it ws.

I'll keep the ticket open for some time and if you spot anything not working properly, let's go through it here - otherwise I'll keep it in some time.

**Comment by Cito** [comment]
Ok, I start to understand. The installer tries to have pyzmq use the system installed libzmq, and if that fails, uses a libzmq version bundled with pyzmq as extension. So it works anyway, even if libzmq is not installed on the system, and these error messages can be ignored.

Maybe a solution would be to do as the error message suggests, install pyzmq with the `--zmq=bundled` option? Then all these error messages would not appear and Zato would use the bundled libzmq consistently.

Also, I wonder why Zato (gevent-zeromq) still uses pyzmq-static. The [pyzmq-static](https://pypi.python.org/pypi/pyzmq-static) docs say it has become obsolete and you can just use pyzmq.

**Comment by dsuch** [comment]
No one probably notices it because it's just part of the output and doesn't stop the build.

I'm not sure how to invoke pyzmq with the ```--zmq=bundled``` flag from buildout, if it's possible at all, short of checking out pyzmq from source and running setup.py manually.

Let's keep the ticket open because we can do away with pyzmq-static but let's not make it a priority right now.

Thanks.

**Comment by Cito** [comment]
Yes, it's not urgent, but I think this could be improved. As far as I understand, even gevent-zeromq is not needed any more; the [README](https://github.com/tmc/gevent-zeromq) says it's deprecated and alreay handled by pyzmq.

So you can probably remove the parts *gevent_zeromq_patched-src* and *gevent_zeromq_patched-install* and the egg pyzmq-static in the buildout config, and replace it with only a part *pyzmq*. You should be able to feed the install option via the arguments setting of zc.recipe.egg:

    [pyzmq]
    recipe = zc.recipe.egg
    eggs = pyzmq
    arguments = --zmq=bundled

I will test it if I find some time.

**Comment by dsuch** [comment]
> I will test it if I find some time.

That would be great.

Remember, cito-t-ghNNN-update-pyzmq ;-)

By the way:

f - feature
b - bug
t - todo

**Comment by Cito** [comment]
I tried with pyzmq 14.0.6, and made some simple tests using an outgoing ZeroMQ connection. Everything worked nicely - gevent-zeromq and pyzmq-static don't seem to be necessary any more. See pull request.
