### ISSUE TITLE
Error while installing Zato with Kubernetes

### ISSUE THREAD

**Issue by MrCoffey** [zatosource/zato-build#54]
Hi there Guys, first of all, thank you for your amazing job with Zato.

I'm following the guide provided in the Zato page: https://zato.io/docs/3.1/admin/guide/install/py3/kubernetes.html .

But I see three things, first is that the documentation is not updated since the deployment is not named `zato-k8.yaml` anymore but `zato-k8.yaml.template`, also I see an `environment` file with some variables so I guess that the template feeds up from them.

The third one is that once I fill the environment file and try to deploy the Zato I'm receiving the message detailed below:

```
$ kubectl apply -f zato-k8.yaml.template
namespace "zato" configured
error: error converting YAML to JSON: yaml: found unexpected ':'
```

Can you guys point if I am doing something wrong or maybe I missing any step?

Thank you in advance.

**Comment by dsuch** [comment]
Hello @MrCoffey,

thank you for the ticket - I see that you closed it so I am not sure, is there anything that you still need assistance with?

Regards.

**Comment by MrCoffey** [comment]
Hi there @dsuch,

Sorry for the late reply. The error was mine, I didn’t apply Dockerize for building the zato-k8.yaml .

Thank you for your response.
