### ISSUE TITLE
broken url when pulling image from registry - instalation in docker - swarm

### ISSUE THREAD

**Issue by codecore-kadamski** [zatosource/zato-build#62]
https://github.com/zatosource/zato-build/blob/3e2a8ba87c2ec8bb0047aee133c0ffdbdc10f82a/docker/swarm/docker-compose.yml.template#L50

in docker-compose.template is bad url to image:
now is: registry.gitlab.com/zatosource/docker-registry/cloud:3.1.0

but this not work

when we cut last number zero then all fine and we can pull image

template fix: registry.gitlab.com/zatosource/docker-registry/cloud:3.1

**Comment by DimShadoWWW** [comment]
Hello @codecore-kadamski , can you check again? thank you

**Comment by codecore-kadamski** [comment]
@DimShadoWWW Yeah, now is OK, but there are (in swarm option) another problems with run Zato.
