### ISSUE TITLE
cloud dockerfile Missing definition of $(WAITS)

### ISSUE THREAD

**Issue by aixi88** [zatosource/zato-build#64]
cloud dockerfile Missing definition of $(WAITS)，Causes entrypoint.sh file 64 line execution error：
/usr/local/bin/dockerize ${WAITS}

**Comment by aixi88** [comment]
@dsuch  Can you help me solve this problem?  
thanks!

**Comment by DimShadoWWW** [comment]
Hello @aixi88 , please update your image and check if it is working OK now

thanks

**Comment by aixi88** [comment]
Can you update https://github.com/zatosource/zato-build/blob/master/docker/cloud/Dockerfile file, I need to build myself, because access to the internet is very slow in China
thanks！

**Comment by DimShadoWWW** [comment]
The update was done in the file [entrypoint.sh](https://github.com/zatosource/zato-build/blob/master/docker/cloud/entrypoint.sh). Please, try if you can download it and check if it works for you.
Thank you

**Comment by aixi88** [comment]
I got it, thank you.
