### ISSUE TITLE
Tutorial Vagrant script fails

### ISSUE THREAD

**Issue by Stew-rt** [zatosource/zato-build#72]
Vagrant quickstart script from tutorial on site fails to build:
`/master/vagrant/zato-3.2/download.sh`

Exception (looks like ansible)
```
TASK [Zato | Download /opt/zato/zato_start_web_admin] **************************
fatal: [default]: FAILED! => {"changed": false, "dest": "/opt/zato/zato_start_web_admin", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://raw.githubusercontent.com/zatosource/zato-build/main/docker/quickstart/zato_start_web_admin"}
```

most likely because this file does not exist in this repo, it could be "zato_start_dashboard"

**Comment by dsuch** [comment]
Thanks @Stew-rt - this will be looked into soon.

**Comment by DimShadoWWW** [comment]
Hello @Stew-rt ,

Thank you for the report. Please, pull the new changes and try again.

**Comment by Stew-rt** [comment]
I can confirm the vagrant build now works as expected

**Comment by DimShadoWWW** [comment]
Thank you @Stew-rt
