### ISSUE TITLE
Entrypoint.sh script cannot invoke `zato create` commands

### ISSUE THREAD

**Issue by kcleong** [zatosource/zato-build#76]
I am trying the docker swarm config, however I am getting an error during execution of the entrypoint script. 

It seems the entrypoint script which invokes the entities in `zato create` is broken:

```
zato_bootstrap_1  | Zato 3.2+rev.9d107937-py3.8.10-ubuntu.20.04-focal
zato_bootstrap_1  | Checking ODB status before
zato_bootstrap_1  | Did not find any relations.
zato_bootstrap_1  | /opt/zato/current/bin/zato create odb  --verbose  --odb_host postgres --odb_port 5432 --odb_user zato --odb_db_name zato --odb_password change_me postgresql
zato_bootstrap_1  | usage: zato [-h] [--version]
zato_bootstrap_1  |             {apispec,ca,cache,change-password,check-config,component-version,create,create-rest-channel,create-wsx-channel,create-wsx-outconn,crypto,decrypt,delete,delete-rest-channel,delete-wsx-channel,delete-wsx-outconn,encrypt,enmasse,hash,from-config,hl7,set-ide-password,info,openapi,pubsub,reset-totp-key,set-admin-invoke-password,quickstart,service,sso,start,stop,update,wait}
zato_bootstrap_1  |             ...
zato_bootstrap_1  | zato: error: unrecognized arguments: --odb_host postgres --odb_port 5432 --odb_user zato --odb_db_name zato --odb_password change_me postgresql
```

**Comment by dsuch** [comment]
Hello @kcleong,

all the Zato installation methods are documented below:

https://zato.io/en/docs/3.2/admin/guide/install/index.html

For Docker, please use Quickstart:

https://zato.io/en/docs/3.2/admin/guide/install/docker.html

If you are building a distributed environment, e.g. Kubernetes or similar cloud-based environments, you can learn here how to do it:

https://zato.io/en/docs/3.2/arch/guide/production/distributed/index.html

Regards.
